# Generated by Django 5.2 on 2025-04-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_created_at_task_deadline_task_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/8/89/Portrait_Placeholder.png', max_length=500),
        ),
        migrations.AlterField(
            model_name='task',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='tasks.team'),
        ),
    ]
