# Generated by Django 5.2 on 2025-05-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_userprofile_image_alter_task_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='https://upload.wikimedia.org/wikipedia/commons/8/89/Portrait_Placeholder.png', max_length=500, upload_to='profile_pictures'),
        ),
    ]
