# Generated by Django 5.2 on 2025-05-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='profile_pictures/placeholder.png', max_length=500, upload_to='profile_pictures'),
        ),
    ]
